name: Build Snapshot

on:
  push:
    branches:
      - "**"

jobs:
  build-windows-package:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install

      - name: Build Windows packages
        run: |
          npm run publish:win

      - name: Rename Windows packages
        shell: bash
        env:
          PACKAGE_FILE_PREFIX: AriaNg_Native-dev-${{ github.run_id }}
        run: |
          mv dist/AriaNg_Native-*-Windows-x64.exe "dist/${PACKAGE_FILE_PREFIX}-Windows-x64.exe"
          mv dist/AriaNg_Native-*-Windows-x64.7z "dist/${PACKAGE_FILE_PREFIX}-Windows-x64.7z"
          mv dist/AriaNg_Native-*-Windows-x86.exe "dist/${PACKAGE_FILE_PREFIX}-Windows-x86.exe"
          mv dist/AriaNg_Native-*-Windows-x86.7z "dist/${PACKAGE_FILE_PREFIX}-Windows-x86.7z"

      - name: Upload Windows x64 installer artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: dist/AriaNg_Native-dev-${{ github.run_id }}-Windows-x64.exe
          if-no-files-found: error

      - name: Upload Windows x64 archive artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: dist/AriaNg_Native-dev-${{ github.run_id }}-Windows-x64.7z
          if-no-files-found: error

      - name: Upload Windows x86 installer artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: dist/AriaNg_Native-dev-${{ github.run_id }}-Windows-x86.exe
          if-no-files-found: error

      - name: Upload Windows x86 archive artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: dist/AriaNg_Native-dev-${{ github.run_id }}-Windows-x86.7z
          if-no-files-found: error

  build-macos-package:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install

      - name: Build macOS packages
        run: |
          npm run publish:osx

      - name: Rename macOS packages
        env:
          PACKAGE_FILE_PREFIX: AriaNg_Native-dev-${{ github.run_id }}
        run: |
          mv dist/AriaNg_Native-*-macOS-arm64.dmg "dist/${PACKAGE_FILE_PREFIX}-macOS-arm64.dmg"
          mv dist/AriaNg_Native-*-macOS-x64.dmg "dist/${PACKAGE_FILE_PREFIX}-macOS-x64.dmg"

      - name: Upload macOS arm64 artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: dist/AriaNg_Native-dev-${{ github.run_id }}-macOS-arm64.dmg
          if-no-files-found: error

      - name: Upload macOS x64 artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: dist/AriaNg_Native-dev-${{ github.run_id }}-macOS-x64.dmg
          if-no-files-found: error
